package pl.grupakpkpur.awslab.model.logging;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedJson;
import lombok.Data;

import java.util.Date;

@DynamoDBTable(tableName = "LogEntry")
@Data
public class LogEntry {

	public static LogEntry fromRequest(LogEntryRequest request) {
		LogEntry entry = new LogEntry();
		entry.setDate(request.date());
		entry.setIp(request.ip());
		entry.setUrl(request.url());
		entry.setMethod(request.method());
		entry.setBody(request.body());
		entry.setUserId(request.userId());
		entry.setUserName(request.userName());

		return entry;
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	private Date date;
	private String ip;
	private String url;
	private String method;

	@DynamoDBTypeConvertedJson
	private Object body;
	private Long userId;
	private String userName;
}
